### ISSUE TITLE
Cannot read csv properly

### ISSUE THREAD

**Issue by anmolbhardwaj17** [ssmahavadi/spotify-mood-classification#1]
Hey! I was trying your project but while making audio dataFrame in normalization.py I was getting an error as 
ValueError: could not convert string to float: '9 Crimes'
How do I resolve this?

**Comment by ssmahavadi** [comment]
Hello and thank you for bringing this issue to my attention! After reviewing my code, I realized I had used the wrong dataset for normalization. Previously, the dataset included qualitative values such as the names of songs (like '9 crimes'), the artist name, etc; these values, for obvious reasons, cannot be normalized. 
To fix this issue, I uploaded a new file to the repository titled 'quanitified_dataset.csv' that should work. Once I normalized this dataset, I reattached the moods to the songs in order to train my KNN module (this can be found in the 'training_data.csv' file). 
Thanks!

**Comment by anmolbhardwaj17** [comment]
Great!
